apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: airsel-micro-webapp
  name: airsel-micro-webapp
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels:
      app: airsel-micro-webapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: airsel-micro-webapp
    spec:
      containers:
      - image: syafiqpipe/airsel-micro-webapp:1.0.21
        imagePullPolicy: Always   
        name: airsel-micro-webapp
        resources: {}
        terminationMessagePath: /micro/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30