# Generated by Django 2.2 on 2020-11-30 23:49

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='measurement_types',
        ),
        migrations.AddField(
            model_name='asset',
            name='measurement_types',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
