# Generated by Django 2.2 on 2020-11-23 10:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(max_length=100)),
                ('badge_number', models.CharField(max_length=100)),
                ('current_value', models.CharField(max_length=100)),
                ('measurent_identifier', models.CharField(max_length=100)),
                ('measurent_type', models.CharField(max_length=100)),
                ('initial_value_flag', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('owning_organization', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_id', models.CharField(max_length=100)),
                ('completion_datetime', models.DateTimeField()),
                ('response', models.CharField(max_length=100)),
                ('response_checkbox', models.CharField(max_length=100)),
                ('response_radio', models.CharField(max_length=100)),
                ('response_date', models.CharField(max_length=100)),
                ('measurement_type', models.CharField(max_length=100)),
                ('reading_type', models.CharField(max_length=100)),
                ('reading_datetime', models.DateTimeField(null=True)),
                ('current_value', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('long_description', models.TextField(max_length=512)),
                ('required_by_date', models.DateField(auto_now=True)),
                ('approval_profile', models.CharField(max_length=100)),
                ('bo', models.CharField(max_length=100)),
                ('downtime_start', models.DateTimeField(null=True)),
                ('planner', models.CharField(max_length=100)),
                ('work_class', models.CharField(max_length=100)),
                ('work_category', models.CharField(max_length=100)),
                ('work_priority', models.IntegerField(default=1)),
                ('requestor', models.CharField(max_length=100)),
                ('owning_access_group', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('primary_phone', models.CharField(max_length=100)),
                ('mobile_phone', models.CharField(max_length=100)),
                ('home_phone', models.CharField(max_length=100)),
                ('node_id', models.CharField(max_length=100)),
                ('asset_id', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('short_text', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('tyle', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valid_value_wo', to='operations.WorkOrderActivity')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_history_type', models.CharField(max_length=100)),
                ('effective_datetime', models.DateTimeField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('comments', models.CharField(max_length=100)),
                ('failure_type', models.CharField(max_length=100)),
                ('failure_mode', models.CharField(max_length=100)),
                ('failure_repair', models.CharField(max_length=100)),
                ('failure_component', models.CharField(max_length=100)),
                ('failure_root_cause', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_history_wo', to='operations.WorkOrderActivity')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('short_text', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('tyle', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_wo', to='operations.WorkOrderActivity')),
            ],
        ),
        migrations.CreateModel(
            name='AssetLocationAssetList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=100)),
                ('asset_id', models.CharField(max_length=100)),
                ('participant', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_location_asset_list_wo', to='operations.WorkOrderActivity')),
            ],
        ),
    ]
