# Generated by Django 2.2 on 2020-10-27 23:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(default='NA', max_length=100)),
                ('badge_number', models.CharField(default='NA', max_length=100)),
                ('current_value', models.CharField(default='NA', max_length=100)),
                ('measurent_identifier', models.CharField(default='NA', max_length=100)),
                ('measurent_type', models.CharField(default='NA', max_length=100)),
                ('initial_value_flag', models.CharField(default='NA', max_length=100)),
                ('owning_organization', models.CharField(default='NA', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(default='NA', max_length=100)),
                ('long_description', models.TextField(default='NA', max_length=512)),
                ('required_by_date', models.DateField(auto_now=True)),
                ('approval_profile', models.CharField(default='NA', max_length=100)),
                ('bo', models.CharField(default='NA', max_length=100)),
                ('downtime_start', models.DateTimeField(null=True)),
                ('planner', models.CharField(default='NA', max_length=100)),
                ('work_class', models.CharField(default='NA', max_length=100)),
                ('work_category', models.CharField(default='NA', max_length=100)),
                ('work_priority', models.IntegerField(default=1)),
                ('requestor', models.CharField(default='NA', max_length=100)),
                ('owning_access_group', models.CharField(default='NA', max_length=100)),
                ('first_name', models.CharField(default='NA', max_length=100)),
                ('last_name', models.CharField(default='NA', max_length=100)),
                ('primary_phone', models.CharField(default='NA', max_length=100)),
                ('mobile_phone', models.CharField(default='NA', max_length=100)),
                ('home_phone', models.CharField(default='NA', max_length=100)),
                ('node_id', models.CharField(default='NA', max_length=100)),
                ('asset_id', models.CharField(default='NA', max_length=100)),
                ('created_by', models.CharField(default='NA', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
