# Generated by Django 2.2 on 2020-11-30 23:49

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderactivity',
            name='asset_location_asset_list',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='workorderactivity',
            name='questions',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='workorderactivity',
            name='service_histories',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='workorderactivity',
            name='valid_values',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
